---
title: "Network Neuroscience"
teaching: 10
exercises: 2
---

[**Download Chapter notebook (ipynb)**](04-section4.ipynb)

:::::::::::::::::::::::::::::::::::::: questions 

- How are graphs represented?
- How are graphs visualised?
- How can graphs be quantitatively analysed?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Understanding the notion of a graph
- Explaining nodes and edges of a network
- Visualising graphs in different layouts

::::::::::::::::::::::::::::::::::::::::::::::::

## Introduction to Networks

In this lesson, we will build and represent networks in Python using __NetworkX__ package.

NetworkX is a Python package for the creation, manipulation, and study of the structure, dynamics, and functions of complex networks.

To use NetworkX and visualise your networks, you can import the whole package.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
use_python("/Users/sabaferdous/envL2D/bin/python3")
#use_virtualenv("r-env")
```

```{python}
import networkx as nx
```

### **Nodes and Edges**

Nodes are the fundamental units of a network. They are linked to other nodes by edges, which show the way(s) in which the nodes are connected or related to one another. In principle, any object, person, cell or brain region can be a node.

The goal of network science is to obtain a representation of connections or interactions between nodes, by using graphs. 

Let’s start by creating an empty graph object, and adding some nodes to it.

```{python}
firstGraph = nx.Graph()

firstGraph.add_node('Node A')
firstGraph.add_node('Node B')
firstGraph.add_node('Node C')

print(firstGraph.nodes)
```

We have created a graph called firstGraph, added three nodes, and then printed a list of the nodes in this graph. So far, these nodes have no relationship to each other. To specify relationships (representing e.g. interactions) we can add edges to show how the nodes are connected.

```{python}
firstGraph.add_edge('Node A', 'Node B')
firstGraph.add_edge('Node A', 'Node C')
firstGraph.add_edge('Node B', 'Node C')

print(firstGraph.edges)
```

Here we created edges between Nodes A and B, A and C, and B and C, and printed a list of these edges. At this stage, our graph has three nodes and three edges. 

### **Visualising networks**

Using the basic graph (firstGraph) that we created, we can begin by visualising it. In NetworkX, we can use function `draw_networkx`.

```{python}
from matplotlib.pyplot import show

nx.draw_networkx(firstGraph)

show()
```

To change the size and the colour of the node symbols:

```{python}
nx.draw_networkx(firstGraph, node_size=2000, node_color='r')

show()
```

### **Complex Networks**

Typically, networks are not set up node by node. Here is an example of a function that creates a fully connected network with a pre-specified number of nodes: all possible edges between the nodes are realised.

```{python}
nodes = 10

Graph = nx.complete_graph(nodes)

layout = nx.circular_layout(Graph)

nx.draw_networkx(Graph, pos=layout)

show()
```

And here is network where connections are drawn randomly but with a pre-defined probability, a random network.

```{python}
edge_probability = 0.5

ER = nx.erdos_renyi_graph(nodes, edge_probability, seed=123)

layout = nx.spring_layout(ER)

nx.draw_networkx(ER, pos=layout)

show()
```

Change the edge probability and see how the network changes.

```{python}
edge_probability = 0.1

ER = nx.erdos_renyi_graph(nodes, edge_probability, seed=123)

layout = nx.spring_layout(ER)

nx.draw_networkx(ER, pos=layout)

show()
```

## The C. elegans Neuron Network

Using the above concepts, we can now have a look at the neuron network of C. elegans.

[Introduction to C elegans neurons](http://www.wormbook.org/chapters/www_celegansintro/celegansintro.html#sec5.4)

[C elegans neurons in the worm atlas](https://www.wormatlas.org/hermaphrodite/nervous/Neuroframeset.html)

<p style='text-align: justify;'>
Caenorhabditis elegans (C. elegans) is a nematode used as model organism to study developmental biology, and specifically neuronal development. It is one of the simplest organisms with a nervous system, which makes it particularly suited for this research. The complete connectome (neuronal map) has been published, originally by White, Southgate, Thomson, and Brenner in 1986, and continues to be researched. 
</p>

<p style='text-align: justify;'>
In this section we are going to use some simplified data from the Dynamic Connectome lab on the neuronal networks of C. elegans. For simplicity, these data have been edited such that only the first 50 of the 131 documented neurons are included. The Python Pandas library is used to import this data. 
</p>

To analyse and display the neural network of C. elegans, we take neurons to represent __nodes__ and synapses to represent __edges__ of a network. 

### **Import Connectivity Data and Labels**
<p style='text-align: justify;'>
The information is provided in the form of a so-called network or connectivity matrix. The matrix shows how neurons connect to each other. We can import the connectivity matrix from the file `celegans131matrix_50.csv`. To find out how many neurons it represents, we check using `len`. 
</p>

```{python}
from pandas import read_csv

data = read_csv('data/celegans131matrix_50.csv', header=None, dtype = "int")

neurons = data.to_numpy()

len(neurons)
```

This is a connectivity matrix for 50 neurons. To display the matrix, we can use the Matplotlib function `imshow()`.

```{python}
from matplotlib.pyplot import subplots, show

fig, ax = subplots()

im = ax.imshow(neurons);

fig.colorbar(im, ticks=(0, 1), shrink=0.5);

show()
```

Each yellow square (representing "1") indicates a connection from the neuron with the index in the rows to a neuron with the index in the columns. 
<p style='text-align: justify;'>
Next, we import the labels and convert the resulting dataframe into a dictionary using function `to_dict`. This is a complex Python array, where the index of each neuron is associated with the name of it. The function `to_dict` wraps the dictionary within a dictionary and therefore indexing is used to access the `inner` dict.
</p>

```{python}
neuron_Names = read_csv('data/celegans131labels_50.csv', header=None)

neuronNames = neuron_Names.to_dict()

neuronLabels = neuronNames[0]

print(neuronLabels)

```

### **C. elegans Network Display**

The connectivity matrix can directly be converted to a Networkx graph.

- First, a Graph object is created, `neuronGraph`

- Second, a network layout is specifided, `neurinLayout`

- Third, the network is plotted with function`draw_networkx`

```{python}
neuronGraph  = nx.from_numpy_matrix(neurons, 
                                    create_using=nx.DiGraph)   

neuronLayout = nx.random_layout(neuronGraph, seed=12)

nx.draw_networkx(neuronGraph, neuronLayout, 
        node_size=1000,
        labels=neuronLabels)
        
show()        
```

The network can be displayed in different layouts, for instance circular:

```{python}
neuronGraph  = nx.from_numpy_matrix(neurons, 
                                    create_using=nx.DiGraph)   

neuronLayout = nx.circular_layout(neuronGraph)

nx.draw_networkx(neuronGraph, neuronLayout, 
        node_size=1000,
        labels=neuronLabels)
show()        
```

### **Quantitative Analysis**
Quantitative analysis of the network is also possible. For instance, we can plot the number of connections that each neuron has:

```{python}

fig, ax = subplots()

ax.plot(dict(neuronGraph.degree).values(), '-o');
ax.set_xlabel('Index');
ax.set_ylabel('Degree');

show()
```


## Anatomical Mapping
<p style='text-align: justify;'>
File `celegans131positions_50.csv` contains information on how the nodes relate to each other in 2-D space. Because in neuroscience, the spatial position in an organism or in the brain is crucial for interpretation, we can include positional information to replace the arbitrary layout of the networks.
</p>

```{python}
neuronPos = read_csv('data/celegans131positions_50.csv', header=None)

neuronPos.items
```

```{python}
nx.draw_networkx(neuronGraph, neuronPos.values,
        node_size=1000,
        labels=neuronLabels)
show()
```


```{python}
new_pos = neuronPos.copy()
new_pos.values[:, 0] = -1*neuronPos.values[:, 0]

nx.draw_networkx(neuronGraph, new_pos.values,
        node_size=1000,
        labels=neuronLabels)
show()        
```

The two BAG nodes to the right of the display are the [sensory neurons used to monitor oxygen and carbon dioxide](https://www.wormatlas.org/neurons/Individual%20Neurons/BAGframeset.html).

Here is some background:
[BAG genes, functions and connections](http://wormweb.org/neuralnet#c=BAG&m=1)

The graph display is in Matplotlib and can be handled as such. E.g. for possible Node shapes see:
https://matplotlib.org/stable/api/markers_api.html#module-matplotlib.markers. 

If you have a multi-panel figure, specify the axes for the network with keyword argument `ax`:

```{python}
fig, ax = subplots(figsize=(14, 8), ncols=2)

nx.draw_networkx(neuronGraph, neuronLayout, 
        node_size=1000,
        labels=neuronLabels,
        ax=ax[0])

nx.draw_networkx(neuronGraph, neuronPos.values,
        node_shape='H',
        node_color='tomato',
        node_size=1300,
        labels=neuronLabels,
        ax=ax[1])

ax[0].set_title('Circular view of C elegans network');
ax[1].set_title('Anatomical view of C elegans network');

show()
```

This concludes out short introduction to networks in the context of neurocsience. Importantly, edges or relationships can also be deduced an a purely functional basis, i.e. even if there is no physical connection between nodes. This is currently one of the most active field of research. 

:::::::::::::::::::::::::::::::::::::keypoints 

- Python package NetworkX is designed to set up and study graphs.
- `draw_networkx` is a NetworkX function to visualise graphs.
- Connectivity information is stored in the connectivity (adjacency) matrix.

::::::::::::::::::::::::::::::::::::::::::::::::
[r-markdown]: https://rmarkdown.rstudio.com/
